DROP DATABASE IF EXISTS autosalonDB;

CREATE DATABASE autosalonDB;
use autosalondb;

    CREATE TABLE FIRMA (
        NAZIV VARCHAR(50),
        CONSTRAINT PK_NAZIV PRIMARY KEY (NAZIV)
    );

    CREATE TABLE MARKA (
        IME VARCHAR(50),
        NAZIV_FIRME VARCHAR(50),
        CONSTRAINT PK_MARKA PRIMARY KEY (IME),
        CONSTRAINT FK_MARKA FOREIGN KEY (NAZIV_FIRME) REFERENCES FIRMA (NAZIV)  ON UPDATE CASCADE ON DELETE CASCADE
    );

    CREATE TABLE AUTO (
        REG_BR VARCHAR(50),
        KUBIKAZA INT (4),
        IME_MARKE VARCHAR(5O),
        CONSTRAINT PK_AUTO PRIMARY KEY(REG.BR),
        CONSTRAINT FK_AUTO FOREIGN KEY(IME_MARKE) REFERENCES MARKA (IME)  ON UPDATE CASCADE ON DELETE CASCADE
    );

    CREATE TABLE SSS (
        NAZIV VARCHAR(50),
        CONSTRAINT PK_SSS PRIMARY KEY (NAZIV)
    );

    CREATE TABLE ZAPOSLENI (
        JMBG INT(13),
        CONSTRAINT PK_ZAPOSLENI PRIMARY KEY (JMBG)
    );

    CREATE TABLE RADNIK_NA_ODRZAVANJU (
        JMBG INT(13),
        PLATA FLOAT(20),
        CONSTRAINT PK_RADNIK PRIMARY KEY (JMBG)
    );

    CREATE TABLE PRODAVCI (
        JMBG INT(13),
        NAZIV_SSS VARCHAR(50),
        CONSTRAINT PK_PRODAVAC PRIMARY KEY (JMBG),
        CONSTRAINT FK_PRODAVAC FOREIGN KEY (NAZIV_SSS) REFERENCES SSS(NAZIV)  ON UPDATE CASCADE ON DELETE CASCADE
    );

    CREATE TABLE STRANKA (
        IME VARCHAR (50),
        TELEFON INT (20),
        ADRESA VARCHAR (50),
        CONSTRAINT PK_STRANKA PRIMARY KEY (IME)
    );

    CREATE TABLE VIP (
        POPUST INT(20),
        STRANKA_IME VARCHAR (50),
        CONSTRAINT PK_VIP PRIMARY KEY (POPUST),
        CONSTRAINT FK_VIP FOREIGN KEY (STRANKA_IME) REFERENCES STRANKA(IME)  ON UPDATE CASCADE ON DELETE CASCADE
    );

    CREATE TABLE UGOVOR (
        ID VARCHAR (50),
        CIJENA INT(30),
        ROK_PLACANJA VARCHAR (50),
        REG_BR VARCHAR (50),
        IME_STRANKE VARCHAR (50),
        PRODAVAC_JMBG INT (13),
        CONSTRAINT PK_ID PRIMARY KEY (ID),
        CONSTRAINT FK_REG FOREIGN KEY (REG_BR) REFERENCES AUTO(REG_BR)  ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT FK_IME_STRANKE FOREIGN KEY (IME_STRANKE) REFERENCES STRANKA(IME)  ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT FK_PRODAVAC FOREIGN KEY (PRODAVAC_JMBG) REFERENCES PRODAVCI(JMBG)  ON UPDATE CASCADE ON DELETE CASCADE
    );